"""empty message

Revision ID: 919bfe80c5f5
Revises: 025786338726
Create Date: 2023-11-30 22:34:37.236072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919bfe80c5f5'
down_revision: Union[str, None] = '025786338726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('all', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practicemark',
    sa.Column('group', sa.String(length=10), nullable=True),
    sa.Column('fio', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studymark',
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('pair_number', sa.Integer(), nullable=True),
    sa.Column('mark', sa.String(length=1), nullable=True),
    sa.Column('is_in_last_month', sa.Boolean(), nullable=False),
    sa.Column('mark_num_index', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=10), nullable=True),
    sa.Column('fio', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('marks')
    op.drop_table('mailings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('course', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('all', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mailings_pkey')
    )
    op.create_table('marks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fio', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pair_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mark', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('group', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('course', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_in_last_month', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mark_num_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='marks_pkey')
    )
    op.drop_table('studymark')
    op.drop_table('practicemark')
    op.drop_table('mailing')
    # ### end Alembic commands ###
