"""empty message

Revision ID: df30b04b5616
Revises: 
Create Date: 2023-11-26 20:15:17.635644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df30b04b5616'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('pair_number', sa.Integer(), nullable=True),
    sa.Column('mark', sa.String(length=1), nullable=True),
    sa.Column('group', sa.String(length=10), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('is_in_last_month', sa.Boolean(), nullable=False),
    sa.Column('mark_num_index', sa.Integer(), nullable=False),
    sa.Column('fio_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    # ### end Alembic commands ###
