"""empty message

Revision ID: f312d08cc604
Revises: 919bfe80c5f5
Create Date: 2023-11-30 22:53:23.891287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f312d08cc604'
down_revision: Union[str, None] = '919bfe80c5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practicemark', sa.Column('course', sa.Integer(), nullable=False))
    op.add_column('studymark', sa.Column('course', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studymark', 'course')
    op.drop_column('practicemark', 'course')
    # ### end Alembic commands ###
